#!/bin/bash

print_top10_common() {
	echo "TOP 10 files of maximum size arranged in descending order (path, size and type):"
	for (( i=1; i <= 10; i++ )); do
		local current_top=$(find $1 2>/dev/null -type f -exec du -h {} + | sort -rh | head -10 | sed "${i}q;d")
		if ! [[ -z $current_top ]]; then
			echo -n "$i - "
			echo -n "$(echo $current_top | awk '{print $2}'), "
	  		echo -n "$(echo $current_top | awk '{print $1}'), "
	  		echo "$(echo $current_top | grep -m 1 -o -E "\.[^/.]+$" | awk -F . '{print $2}')"
		fi
	done
}

print_top10_exec() {
	echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file):"
	for (( i=1; i <= 10; i++ )); do
		local current_top=$(find $1 2>/dev/null -type f -executable -exec du -h {} + | sort -rh | head -10 | sed "${i}q;d")
		if ! [[ -z $current_top ]]; then
			local path=$(echo $current_top | awk '{print $2}')
			local MD5=$(md5sum $path | awk '{print $1}')
			echo -n "$i - "
			echo -n "$(echo $current_top | awk '{print $2}'), "
			echo -n "$(echo $current_top | awk '{print $1}'), "
			echo "$MD5"
		fi
	done
}
